services:
  dev-db:
    image: postgres:18.2-trixie
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=dev_db
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_pass
      - PGDATA=/var/lib/postgresql/data/pgdata

volumes:
  dev-db-data: