name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/graalvm/graalvm-community:25.0.2
    steps:
      - uses: actions/checkout@v6

      - name: Build native image
        run: |
          ./gradlew nativeCompile

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Install gcloud CLI
        uses: google-github-actions/setup-gcloud@v3
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Upload native binary
        run: |
          gcloud storage cp build/native/nativeCompile/spring-server gs://${{ secrets.GCP_BUCKET_NAME }}/spring-server
