name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/graalvm/graalvm-community:25.0.2

    steps:
      - uses: actions/checkout@v6

      - name: Restore native cache
        id: native-cache
        uses: actions/cache/restore@v4
        with:
          path: build/native/nativeCompile/spring-server
          key: native-${{ runner.arch }}-${{ github.sha }}

      - name: Prevent double build if cache exists
        if: steps.native-cache.outputs.cache-hit == 'true'
        run: |
          echo "Cache for this commit SHA already exists. Skipping build."
          exit 1

      - name: Build native image
        run: ./gradlew nativeCompile

      - name: Save native cache
        uses: actions/cache/save@v4
        with:
          path: build/native/nativeCompile/spring-server
          key: native-${{ runner.arch }}-${{ github.sha }}
