name: CD

on:
  workflow_dispatch:

jobs:
  cd:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6

      - name: Install GraalVM CE
        run: |
          JAVA_HOME=/opt/java/25.0.2-graalce
          
          curl -L -o graalce.tar.gz https://github.com/graalvm/graalvm-ce-builds/releases/download/jdk-25.0.2/graalvm-community-jdk-25.0.2_linux-x64_bin.tar.gz
          
          mkdir -p $JAVA_HOME
          tar -xzf graalce.tar.gz -C $JAVA_HOME --strip-components=1
          rm graalce.tar.gz
          
          echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV
          echo "$JAVA_HOME/bin" >> $GITHUB_PATH

      - name: Cache native build
        id: native-cache
        uses: actions/cache@v5
        with:
          path: build/native/nativeCompile/spring-server
          key: native-${{ runner.arch }}-test

      - name: Build native image
        run: |
          if [ "${{ steps.native-cache.outputs.cache-hit }}" != "true" ]; then
            ./gradlew nativeCompile
          else
            echo "Cache hit, skipping build."
          fi

      - name: Make executable
        run: chmod +x build/native/nativeCompile/spring-server

      # --- Docker/GCP は必要に応じて有効化 ---
      # - uses: google-github-actions/auth@v3
      #   with:
      #     credentials_json: ${{ secrets.GCP_SA_KEY }}
      #
      # - uses: google-github-actions/setup-gcloud@v3
      #   with:
      #     project_id: ${{ secrets.GCP_PROJECT_ID }}
      #     export_default_credentials: true
      #
      # - name: Configure Docker
      #   run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev
      #
      # - name: Build and Push Docker image
      #   run: |
      #     docker build -t ${{ secrets.DOCKER_IMAGE }}:latest .
      #     docker push ${{ secrets.DOCKER_IMAGE }}:latest
