name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Install gcloud CLI
        uses: google-github-actions/setup-gcloud@v3
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Download native binary
        run: |
          mkdir -p build/native/nativeCompile
          gcloud storage cp gs://${{ secrets.GCP_BUCKET_NAME }}/spring-server build/native/nativeCompile/spring-server

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev

      - name: Debug - Show current directory
        run: pwd

      - name: Debug - List files in root
        run: ls -la

      - name: Debug - List files in native build folder
        run: ls -la build/native/nativeCompile

      - name: Debug - Check Dockerfile existence
        run: |
          if [ -f build/native/nativeCompile/Dockerfile ]; then
            echo "Dockerfile exists"
          else
            echo "Dockerfile not found!"
            exit 1
          fi

      - name: Build and Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_IMAGE }}:latest .
          docker push ${{ secrets.DOCKER_IMAGE }}:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ secrets.CLOUD_RUN_SERVICE }} \
            --image=${{ secrets.DOCKER_IMAGE }}:latest \
            --region=asia-northeast1
